"""add source_path html_content to documents and sitemap_json to collections

Revision ID: 3d9d149a244c
Revises: 9dd5f96860ba
Create Date: 2026-04-10 12:32:16.757681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9d149a244c'
down_revision: Union[str, Sequence[str], None] = '9dd5f96860ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('sitemap_json', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('html_content', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('source_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source_path')
    op.drop_column('documents', 'html_content')
    op.drop_column('collections', 'sitemap_json')
    # ### end Alembic commands ###
