"""add chat keywords and keyword_occurrences

Revision ID: abb7d532aea4
Revises: a1b2c3d4e5f6
Create Date: 2026-05-05 10:58:50.277254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb7d532aea4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_occurrences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=True),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_keyword_occ_doc', 'keyword_occurrences', ['document_id'], unique=False)
    op.create_index('idx_keyword_occ_kw_doc', 'keyword_occurrences', ['keyword', 'document_id'], unique=False)
    op.create_index(op.f('ix_keyword_occurrences_document_id'), 'keyword_occurrences', ['document_id'], unique=False)
    op.create_index(op.f('ix_keyword_occurrences_keyword'), 'keyword_occurrences', ['keyword'], unique=False)
    op.add_column('documents', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('category', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'total_tokens')
    op.drop_column('documents', 'keywords')
    op.drop_index(op.f('ix_keyword_occurrences_keyword'), table_name='keyword_occurrences')
    op.drop_index(op.f('ix_keyword_occurrences_document_id'), table_name='keyword_occurrences')
    op.drop_index('idx_keyword_occ_kw_doc', table_name='keyword_occurrences')
    op.drop_index('idx_keyword_occ_doc', table_name='keyword_occurrences')
    op.drop_table('keyword_occurrences')
    # ### end Alembic commands ###
