"""add bound_collection_id to chats

Revision ID: c2d4e6f8a0b1
Revises: abb7d532aea4
Create Date: 2026-05-05 12:00:00.000000

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c2d4e6f8a0b1'
down_revision: Union[str, Sequence[str], None] = 'abb7d532aea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('bound_collection_id', sa.String(length=32), nullable=True))
    op.create_index('idx_chats_bound_collection_id', 'chats', ['bound_collection_id'], unique=False)
    op.create_unique_constraint('uq_chats_bound_collection_id', 'chats', ['bound_collection_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chats_bound_collection_id', 'chats', type_='unique')
    op.drop_index('idx_chats_bound_collection_id', table_name='chats')
    op.drop_column('chats', 'bound_collection_id')
    # ### end Alembic commands ###
