"""add colletions.summary and document.summary

Revision ID: 9dd5f96860ba
Revises: 0a776dbea0f7
Create Date: 2025-09-21 10:18:49.924958

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9dd5f96860ba'
down_revision: Union[str, Sequence[str], None] = '0a776dbea0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    op.drop_column('collections', 'summary')
    # ### end Alembic commands ###
